using System.Runtime.Serialization;
using C4Net.Core.Attributes;
using C4Net.Data.Attributes;


namespace C4Net.JC3IEDM.Enums
{
    /// <summary>
    /// The specific value that represents the class of a pressure system in a particular ATMOSPHERE.
    /// </summary>
    [DomId(100000304)]
    [DataContract]
    public enum AtmospherePressureSystemCategoryEnum
    {
		
        /// <summary>
        /// The discontinuity at the forward edge of an advancing cold air mass that is displacing warmer air in its path.
        /// </summary>
        [DomValIx(1000001)]
        [StringValue("CLDFRT")]
        [EnumMember]
        ColdFront,
		
        /// <summary>
        /// An area of high atmospheric pressure that has a closed circulation that is anticyclonic, i.e., as viewed from above, the circulation is clockwise in the Northern Hemisphere, counterclockwise in the southern Hemisphere, undefined at the Equator.
        /// </summary>
        [DomValIx(1000002)]
        [StringValue("HGHPRS")]
        [EnumMember]
        HighPressureCentre,
		
        /// <summary>
        /// 1. An area of low atmospheric pressure that has a closed circulation that is cyclonic, i.e., as viewed from above, the circulation is counterclockwise in the Northern Hemisphere, clockwise in the Southern Hemisphere, undefined at the Equator. Because cyclonic circulation and relatively low atmospheric pressure usually coexist, in common practice the terms cyclone and low are used interchangeably. Also, because cyclones often are accompanied by inclement (sometimes destructive) weather, they are frequently referred to simply as storms. 2. Frequently misused to denote a tornado. 3. In the Indian Ocean, a tropical cyclone of hurricane or typhoon force.
        /// </summary>
        [DomValIx(1000003)]
        [StringValue("LOWPRS")]
        [EnumMember]
        LowPressureCentre,
		
        /// <summary>
        /// The line along which a cold front has overtaken a warm front at ground level.
        /// </summary>
        [DomValIx(1000004)]
        [StringValue("OCCFRT")]
        [EnumMember]
        OccludedFront,
		
        /// <summary>
        /// An elongated region of high atmospheric pressure.
        /// </summary>
        [DomValIx(1000005)]
        [StringValue("RDGLIN")]
        [EnumMember]
        RidgeLine,
		
        /// <summary>
        /// A line of high winds and thunderstorms in convectively unstable air, an instability line (of non-frontal nature); it may be generated by a cold front.
        /// </summary>
        [DomValIx(1000006)]
        [StringValue("SQLLIN")]
        [EnumMember]
        SquallLine,
		
        /// <summary>
        /// A situation in which the surface position of a front does not move; the flow on either side of such a boundary is nearly parallel to the position of the front.
        /// </summary>
        [DomValIx(1000007)]
        [StringValue("STAFRT")]
        [EnumMember]
        StationaryFront,
		
        /// <summary>
        /// An elongated region of low atmospheric pressure.
        /// </summary>
        [DomValIx(1000008)]
        [StringValue("TRGLIN")]
        [EnumMember]
        TroughLine,
		
        /// <summary>
        /// Occurs when discontinuity at the forward edge of an advancing cold air mass is displacing warmer air in its path and the two air masses intersect above ground level.
        /// </summary>
        [DomValIx(1000009)]
        [StringValue("UPCFRT")]
        [EnumMember]
        UpperColdFront,
		
        /// <summary>
        /// Occurs when discontinuity at the forward edge of an advancing warm air mass is displacing cooler air in its path and the two air masses intersect above ground level.
        /// </summary>
        [DomValIx(1000010)]
        [StringValue("UPWFRT")]
        [EnumMember]
        UpperWarmFront,
		
        /// <summary>
        /// The discontinuity at the forward edge of an advancing warm air mass that is displacing cooler air in its path.
        /// </summary>
        [DomValIx(1000011)]
        [StringValue("WRMFRT")]
        [EnumMember]
        WarmFront,
		
    }
}
